name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pip3 install Pillow
    - run: pip3 install pycryptodome
    - run: pip3 install numpy
    - run: pip3 install opencv-python
    - run: pip3 install pandas
    - name: test AES
      run: cd src/AES; python3 ./main.py -i ../../images/photo.jpg
    - name: test Halftone
      run: cd src/Halftone; python3 ./halftone.py ../../images/Lenna.jpg; python3 ./halftone_decry.py ./outputs/CMKY_Share3_1.jpg ./outputs/CMKY_Share3_2.jpg ./outputs/CMKY_Share3_3.jpg ./outputs/CMKY_Share3_shareMask.jpg ../../images/Lenna.jpg
    - name: test XOR
      run: cd src/XOR; python3 ./main.py 8 ../../images/Lenna.jpg
    - name: test application
      run: cd application; python3 ./main.py ../images/image1.jpg ../images/image2.jpg ../images/secret.jpg



